// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIchSmxABT1VHV8MBI7-AxCQ4C1JnBn7Q',
    appId: '1:28311975332:web:f19159b416991a6effbd31',
    messagingSenderId: '28311975332',
    projectId: 'tiktok-clone-66131',
    authDomain: 'tiktok-clone-66131.firebaseapp.com',
    storageBucket: 'tiktok-clone-66131.appspot.com',
    measurementId: 'G-954PRG58J6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-MrrxnaVV7US2taPI6Binc0p8MXrNWIY',
    appId: '1:28311975332:android:eb2c628c2e3911d4ffbd31',
    messagingSenderId: '28311975332',
    projectId: 'tiktok-clone-66131',
    storageBucket: 'tiktok-clone-66131.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaFYA-pkZ8J0LZ34RjIA_pf7q65DoRfyM',
    appId: '1:28311975332:ios:6f5013b96eaafa28ffbd31',
    messagingSenderId: '28311975332',
    projectId: 'tiktok-clone-66131',
    storageBucket: 'tiktok-clone-66131.appspot.com',
    iosBundleId: 'com.example.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaFYA-pkZ8J0LZ34RjIA_pf7q65DoRfyM',
    appId: '1:28311975332:ios:9c9982fd616c26afffbd31',
    messagingSenderId: '28311975332',
    projectId: 'tiktok-clone-66131',
    storageBucket: 'tiktok-clone-66131.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
